# 1) Descentes de gradient sans contraintes
-------------------------------------------


Le nombre de conditionnement d'un fonction f(x1, x2) = a*x1² + b*x2²est équivalent au nombre de conditionnement de sa Hessienne

Pour donner une famille de fonction, 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = 1
b = 1

toto = np.array([[2*a, 0], [0, 2*b]])

m = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
nb_cond1 = np.linalg.norm(m) * np.linalg.norm(np.linalg.inv(m))
nb_cond2 = np.linalg.cond(m)

test = m * np.linalg.inv(m)
print(test)
print(np.linalg.inv(m))


print(nb_cond1, "\n", nb_cond2)

[[ 0.5  0.  -0.5]
 [ 0.   1.   0. ]
 [-0.5  0.   0.5]]
[[ 0.5  0.   0.5]
 [ 0.   1.   0. ]
 [-0.5  0.   0.5]]
3.16227766017 
 1.41421356237


In [4]:
def gradient_descent(x, ob_function, d_direction, 
                     rate=(lambda x, y: 0.01),
                     decay_function=(lambda x, y: abs(x[0] - y[0])),
                     tolerance=0.0001, max_iter=1000,
                     plot_f=(lambda x, y: None)):
    """Gradient Descent.
    
    Computes minimal value of a convex function and local minimum of none convex function.
    
    Args:
        x (ndarray): initial starting point for descent.
        ob_function: objective function of optimisation problem, has input ndarray and outputs float.
        d_direction: function computing descent direction, outputs ndarray.
        rate: function computing learning rate, outputs float.
        decay_function: function computing decay, outputs float.
        tolerance (float): slack tolerance.
        max_iter (int): upper bound on number of iterations.      
        plot_f: plotting function for iteration points.
         
    Output:
        (int, int) minimizer, minimal value.
        
    """
    n_iter = 0
    decay = tolerance + 10  # Make sure that we get into first loop
    y = ob_function(x)
    while decay > tolerance and n_iter < max_iter:
        x = x - rate(ob_function, n_iter) * d_direction(ob_function, x)
        tmp_y = ob_function(x)
        decay = decay_function(y, tmp_y)
        y = tmp_y
        n_iter += 1
        plot_f(x, y)
    msg = " Iteration nu. = {}\n approx. = {}\n ob value = {}\n and decay = {}."
    print(msg.format(n_iter, x.flatten(), y[0], decay))
    return (x, y) if decay <= tolerance else warnings.warn("Decay didn't get under tolerance rate.", RuntimeWarning)