# 1) Descentes de gradient sans contraintes
-------------------------------------------


In [21]:
import numpy as np


a = 1
b = 1

toto = np.array([[2*a, 0], [0, 2*b]])

m = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
nb_cond1 = np.linalg.norm(m) * np.linalg.norm(np.linalg.inv(m))
nb_cond2 = np.linalg.cond(m)

test = m * np.linalg.inv(m)
print(test)
print(np.linalg.inv(m))


print(nb_cond1, "\n", nb_cond2)

[[ 0.5  0.  -0.5]
 [ 0.   1.   0. ]
 [-0.5  0.   0.5]]
[[ 0.5  0.   0.5]
 [ 0.   1.   0. ]
 [-0.5  0.   0.5]]
3.1622776601683795 
 1.4142135623730951
